version: '3.9'
services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com,time1.google.com,ntp1.fau.de
      - LOG_LEVEL=0
      - TZ=Europe/Moscow
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntp.entrypoints=http"
      - "traefik.http.routers.ntp.rule=Host(`HOST`)"
      - "traefik.http.middlewares.ntp-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ntp.middlewares=wireguard-https-redirect"
      - "traefik.http.routers.ntp-secure.entrypoints=https"
      - "traefik.http.routers.ntp-secure.rule=Host(`HOST`)"
      - "traefik.http.routers.ntp-secure.tls=true"
      - "traefik.http.routers.ntp-secure.service=ntp"
      - "traefik.http.services.ntp.loadbalancer.server.port=124"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
