version: "3"
services:
  node-red:
    image: nodered/node-red
    container_name: nodered
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/.node-red/data:/data
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=http"
      - "traefik.http.routers.nodered.rule=Host(`DOMAIN`)"
      - "traefik.http.middlewares.nodered-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nodered.middlewares=nodered-https-redirect"
      - "traefik.http.routers.nodered-secure.entrypoints=https"
      - "traefik.http.routers.nodered-secure.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.nodered-secure.tls=true"
      - "traefik.http.routers.nodered-secure.service=nodered"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
